# .github/workflows/nodejs.yml

name: Node.js CI

on:
  push:
    branches: [ main ]
    
jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Cache dependencies
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install server dependencies
      run: npm ci
    - name: Install client dependencies
      run: cd client && npm ci --ignore-scripts
    - name: Build the client
      run: cd client && npm run build
    - name: Server Start
      run: sudo pm2 restart server.js
